<?php
/**
 * Private shared-media bridge.
 *
 * A central read/write mirror worker prepares original images and the exact
 * registered derivative set. WordPress mounts that repository read-only and
 * creates only local attachment records; it never copies or resizes the files.
 *
 * This feature has no admin UI and is enabled only through wp-config constants.
 * PHP 7.4 compatible.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Mobo_Core_Shared_Media {

	private static $last_error = '';

	/**
	 * Register URL, metadata and write-protection filters.
	 *
	 * @return void
	 */
	public static function init() {
		if ( ! self::enabled() ) {
			return;
		}

		add_filter( 'wp_get_attachment_url', array( __CLASS__, 'filter_attachment_url' ), 20, 2 );
		add_filter( 'get_attached_file', array( __CLASS__, 'filter_attached_file' ), 20, 2 );
		add_filter( 'intermediate_image_sizes_advanced', array( __CLASS__, 'filter_intermediate_sizes' ), 100, 3 );
		add_filter( 'big_image_size_threshold', array( __CLASS__, 'filter_big_image_threshold' ), 100, 4 );
		add_filter( 'wp_update_attachment_metadata', array( __CLASS__, 'protect_attachment_metadata' ), 100, 2 );
		add_filter( 'wp_delete_file', array( __CLASS__, 'protect_shared_file_from_delete' ), 100, 1 );
	}

	/**
	 * Whether the private shared-media mode is active.
	 *
	 * Required constants:
	 * - MOBO_CORE_SHARED_MEDIA_ENABLED = true
	 * - MOBO_CORE_SHARED_MEDIA_PATH
	 * - MOBO_CORE_SHARED_MEDIA_URL
	 *
	 * @return bool
	 */
	public static function enabled() {
		return defined( 'MOBO_CORE_SHARED_MEDIA_ENABLED' )
			&& true === (bool) MOBO_CORE_SHARED_MEDIA_ENABLED
			&& '' !== self::base_path()
			&& '' !== self::base_url();
	}

	/**
	 * Whether normal WordPress image downloads are permitted.
	 * Defaults to true for backward compatibility.
	 *
	 * @return bool
	 */
	public static function downloads_enabled() {
		if ( defined( 'MOBO_CORE_IMAGE_DOWNLOAD_ENABLED' ) ) {
			return true === (bool) MOBO_CORE_IMAGE_DOWNLOAD_ENABLED;
		}
		if ( defined( 'MOBO_IMAGE_DOWNLOAD_ENABLED' ) ) {
			return true === (bool) MOBO_IMAGE_DOWNLOAD_ENABLED;
		}
		return true;
	}

	/**
	 * Resolve one shared image and create a site-local attachment record.
	 * No file is copied and no derivative is generated by WordPress.
	 *
	 * @param string $image_guid Remote image ID.
	 * @param string $source_url Source URL from Portal payload.
	 * @param int    $product_id Parent product.
	 * @return int Attachment ID or 0.
	 */
	public static function import_attachment( $image_guid, $source_url, $product_id ) {
		self::$last_error = '';

		if ( ! self::enabled() ) {
			self::$last_error = 'Shared media mode is not enabled.';
			return 0;
		}

		$image_guid = self::normalize_image_id( $image_guid );
		$product_id = absint( $product_id );
		$source_url = esc_url_raw( (string) $source_url );
		if ( '' === $image_guid || $product_id <= 0 ) {
			self::$last_error = 'Invalid shared media image ID or product ID.';
			return 0;
		}

		$existing = self::find_attachment( $image_guid );
		if ( $existing > 0 ) {
			return self::refresh_attachment( $existing, $image_guid, $source_url );
		}

		$manifest = self::load_manifest( $image_guid );
		if ( is_wp_error( $manifest ) ) {
			self::$last_error = $manifest->get_error_message();
			return 0;
		}

		$original = isset( $manifest['original'] ) && is_array( $manifest['original'] ) ? $manifest['original'] : array();
		$relative = self::normalize_relative_path( isset( $original['file'] ) ? $original['file'] : '' );
		$absolute = self::resolve_existing_file( $relative );
		if ( '' === $absolute ) {
			self::$last_error = 'Shared media original file is missing or outside the configured repository.';
			return 0;
		}

		$width  = isset( $original['width'] ) ? absint( $original['width'] ) : 0;
		$height = isset( $original['height'] ) ? absint( $original['height'] ) : 0;
		$mime   = isset( $original['mime'] ) ? sanitize_mime_type( (string) $original['mime'] ) : '';
		if ( $width <= 0 || $height <= 0 || 0 !== strpos( $mime, 'image/' ) ) {
			self::$last_error = 'Shared media manifest has invalid original image metadata.';
			return 0;
		}

		$public_url = self::url_for_relative_file( $relative );
		if ( '' === $public_url ) {
			self::$last_error = 'Shared media URL could not be generated.';
			return 0;
		}

		$post_title = sanitize_text_field( isset( $manifest['title'] ) ? (string) $manifest['title'] : $image_guid );
		if ( '' === $post_title ) {
			$post_title = $image_guid;
		}

		$attachment_id = wp_insert_attachment(
			array(
				'post_mime_type' => $mime,
				'post_title'     => $post_title,
				'post_content'   => '',
				'post_status'    => 'inherit',
				'guid'           => $public_url,
			),
			$absolute,
			$product_id,
			true
		);

		if ( is_wp_error( $attachment_id ) ) {
			self::$last_error = 'Shared media attachment insert failed: ' . $attachment_id->get_error_message();
			return 0;
		}

		$attachment_id = absint( $attachment_id );
		if ( $attachment_id <= 0 ) {
			self::$last_error = 'Shared media attachment insert returned an invalid ID.';
			return 0;
		}

		$metadata = self::build_attachment_metadata( $manifest, $relative, $width, $height );
		update_post_meta( $attachment_id, '_wp_attached_file', $absolute );
		update_post_meta( $attachment_id, '_wp_attachment_metadata', $metadata );
		update_post_meta( $attachment_id, '_mobo_shared_media', '1' );
		update_post_meta( $attachment_id, '_mobo_shared_media_relative_file', $relative );
		update_post_meta( $attachment_id, '_mobo_shared_media_manifest_revision', sanitize_text_field( (string) ( isset( $manifest['revision'] ) ? $manifest['revision'] : '' ) ) );
		update_post_meta( $attachment_id, 'image_guid', $image_guid );
		update_post_meta( $attachment_id, 'img_guid', $image_guid );
		if ( '' !== $source_url ) {
			update_post_meta( $attachment_id, 'mobo_source_url', $source_url );
		}
		update_post_meta( $attachment_id, 'mobo_sync_incomplete', '0' );

		clean_post_cache( $attachment_id );
		return $attachment_id;
	}

	/**
	 * Refresh path, URL and pre-generated metadata of an existing shared attachment.
	 * This is read-only with respect to the shared repository; only WordPress post
	 * metadata is updated when the mirror publishes a new manifest revision.
	 *
	 * @param int    $attachment_id Attachment ID.
	 * @param string $image_guid Remote image ID.
	 * @param string $source_url Source URL.
	 * @return int Attachment ID or 0.
	 */
	public static function refresh_attachment( $attachment_id, $image_guid, $source_url = '' ) {
		self::$last_error = '';
		$attachment_id = absint( $attachment_id );
		$image_guid = self::normalize_image_id( $image_guid );
		$source_url = esc_url_raw( (string) $source_url );
		if ( $attachment_id <= 0 || '' === $image_guid || 'attachment' !== get_post_type( $attachment_id ) ) {
			self::$last_error = 'Invalid shared attachment refresh request.';
			return 0;
		}

		$manifest = self::load_manifest( $image_guid );
		if ( is_wp_error( $manifest ) ) {
			self::$last_error = $manifest->get_error_message();
			return 0;
		}
		$original = isset( $manifest['original'] ) && is_array( $manifest['original'] ) ? $manifest['original'] : array();
		$relative = self::normalize_relative_path( isset( $original['file'] ) ? $original['file'] : '' );
		$absolute = self::resolve_existing_file( $relative );
		$width = isset( $original['width'] ) ? absint( $original['width'] ) : 0;
		$height = isset( $original['height'] ) ? absint( $original['height'] ) : 0;
		$mime = isset( $original['mime'] ) ? sanitize_mime_type( (string) $original['mime'] ) : '';
		if ( '' === $absolute || $width <= 0 || $height <= 0 || 0 !== strpos( $mime, 'image/' ) ) {
			self::$last_error = 'Shared media manifest or original file is invalid.';
			return 0;
		}

		$revision = sanitize_text_field( (string) ( isset( $manifest['revision'] ) ? $manifest['revision'] : '' ) );
		$current_revision = sanitize_text_field( (string) get_post_meta( $attachment_id, '_mobo_shared_media_manifest_revision', true ) );
		$current_relative = self::normalize_relative_path( get_post_meta( $attachment_id, '_mobo_shared_media_relative_file', true ) );
		if ( $revision !== $current_revision || $relative !== $current_relative ) {
			update_post_meta( $attachment_id, '_wp_attached_file', $absolute );
			update_post_meta( $attachment_id, '_wp_attachment_metadata', self::build_attachment_metadata( $manifest, $relative, $width, $height ) );
			update_post_meta( $attachment_id, '_mobo_shared_media_relative_file', $relative );
			update_post_meta( $attachment_id, '_mobo_shared_media_manifest_revision', $revision );
			wp_update_post( array(
				'ID'             => $attachment_id,
				'post_mime_type' => $mime,
			) );
		}
		update_post_meta( $attachment_id, '_mobo_shared_media', '1' );
		update_post_meta( $attachment_id, 'image_guid', $image_guid );
		update_post_meta( $attachment_id, 'img_guid', $image_guid );
		if ( '' !== $source_url ) { update_post_meta( $attachment_id, 'mobo_source_url', $source_url ); }
		clean_post_cache( $attachment_id );
		return $attachment_id;
	}

	/**
	 * Last resolver error for queue diagnostics.
	 *
	 * @return string
	 */
	public static function get_last_error() {
		return sanitize_text_field( (string) self::$last_error );
	}

	/**
	 * Replace WordPress upload URL for shared attachments.
	 *
	 * @param string $url Attachment URL.
	 * @param int    $attachment_id Attachment ID.
	 * @return string
	 */
	public static function filter_attachment_url( $url, $attachment_id ) {
		if ( ! self::is_shared_attachment( $attachment_id ) ) {
			return $url;
		}
		$relative = self::normalize_relative_path( get_post_meta( $attachment_id, '_mobo_shared_media_relative_file', true ) );
		$shared   = self::url_for_relative_file( $relative );
		return '' !== $shared ? $shared : $url;
	}

	/**
	 * Return the external read-only absolute path.
	 *
	 * @param string $file Existing path.
	 * @param int    $attachment_id Attachment ID.
	 * @return string
	 */
	public static function filter_attached_file( $file, $attachment_id ) {
		if ( ! self::is_shared_attachment( $attachment_id ) ) {
			return $file;
		}
		$relative = self::normalize_relative_path( get_post_meta( $attachment_id, '_mobo_shared_media_relative_file', true ) );
		$resolved = self::resolve_existing_file( $relative );
		return '' !== $resolved ? $resolved : $file;
	}

	/**
	 * Never generate WordPress subsizes for a shared attachment.
	 *
	 * @param array $sizes Sizes.
	 * @param array $image_meta Metadata.
	 * @param int   $attachment_id Attachment ID.
	 * @return array
	 */
	public static function filter_intermediate_sizes( $sizes, $image_meta, $attachment_id ) {
		return self::is_shared_attachment( $attachment_id ) ? array() : $sizes;
	}

	/**
	 * Disable big-image scaling for files inside the shared repository.
	 *
	 * @param int|false $threshold Threshold.
	 * @param array     $imagesize Image size.
	 * @param string    $file File.
	 * @param int       $attachment_id Attachment ID.
	 * @return int|false
	 */
	public static function filter_big_image_threshold( $threshold, $imagesize, $file, $attachment_id ) {
		if ( self::is_shared_attachment( $attachment_id ) || self::is_path_inside_repository( $file ) ) {
			return false;
		}
		return $threshold;
	}

	/**
	 * Preserve manifest-generated metadata against regeneration plugins.
	 *
	 * @param array $data New metadata.
	 * @param int   $attachment_id Attachment ID.
	 * @return array
	 */
	public static function protect_attachment_metadata( $data, $attachment_id ) {
		if ( ! self::is_shared_attachment( $attachment_id ) ) {
			return $data;
		}
		$current = get_post_meta( $attachment_id, '_wp_attachment_metadata', true );
		return is_array( $current ) && ! empty( $current ) ? $current : $data;
	}

	/**
	 * Allow attachment records to be deleted without deleting the shared file.
	 *
	 * @param string $file File path.
	 * @return string
	 */
	public static function protect_shared_file_from_delete( $file ) {
		return self::is_path_inside_repository( $file ) ? '' : $file;
	}

	/**
	 * @param int $attachment_id Attachment ID.
	 * @return bool
	 */
	public static function is_shared_attachment( $attachment_id ) {
		return absint( $attachment_id ) > 0 && '1' === (string) get_post_meta( $attachment_id, '_mobo_shared_media', true );
	}

	private static function build_attachment_metadata( $manifest, $relative, $width, $height ) {
		$metadata = array(
			'width'      => $width,
			'height'     => $height,
			'file'       => $relative,
			'sizes'      => array(),
			'image_meta' => array(),
		);

		$sizes = isset( $manifest['sizes'] ) && is_array( $manifest['sizes'] ) ? $manifest['sizes'] : array();
		foreach ( $sizes as $name => $row ) {
			if ( ! is_array( $row ) ) {
				continue;
			}
			$size_relative = self::normalize_relative_path( isset( $row['file'] ) ? $row['file'] : '' );
			$absolute      = self::resolve_existing_file( $size_relative );
			$size_width    = isset( $row['width'] ) ? absint( $row['width'] ) : 0;
			$size_height   = isset( $row['height'] ) ? absint( $row['height'] ) : 0;
			$size_mime     = isset( $row['mime'] ) ? sanitize_mime_type( (string) $row['mime'] ) : 'image/webp';
			if ( '' === $absolute || $size_width <= 0 || $size_height <= 0 ) {
				continue;
			}
			$metadata['sizes'][ sanitize_key( (string) $name ) ] = array(
				'file'      => basename( $size_relative ),
				'width'     => $size_width,
				'height'    => $size_height,
				'mime-type' => $size_mime,
			);
		}

		return $metadata;
	}

	private static function load_manifest( $image_guid ) {
		$shard = self::shard( $image_guid );
		$path  = self::base_path() . '/metadata/' . $shard . '/' . $image_guid . '.json';
		$real  = realpath( $path );
		if ( false === $real || ! self::is_path_inside_repository( $real ) || ! is_readable( $real ) ) {
			return new WP_Error( 'mobo_shared_manifest_missing', 'Shared media manifest is not available yet.' );
		}

		$raw = file_get_contents( $real );
		if ( false === $raw || '' === trim( $raw ) || strlen( $raw ) > 256 * 1024 ) {
			return new WP_Error( 'mobo_shared_manifest_invalid', 'Shared media manifest is empty or too large.' );
		}

		$data = json_decode( $raw, true );
		if ( ! is_array( $data ) || 1 !== absint( isset( $data['schemaVersion'] ) ? $data['schemaVersion'] : 0 ) ) {
			return new WP_Error( 'mobo_shared_manifest_schema', 'Shared media manifest schema is invalid.' );
		}
		if ( self::normalize_image_id( isset( $data['imageId'] ) ? $data['imageId'] : '' ) !== $image_guid ) {
			return new WP_Error( 'mobo_shared_manifest_identity', 'Shared media manifest image ID does not match.' );
		}

		if ( defined( 'MOBO_CORE_SHARED_MEDIA_PROFILE_HASH' ) && '' !== trim( (string) MOBO_CORE_SHARED_MEDIA_PROFILE_HASH ) ) {
			$profile_hash = sanitize_text_field( (string) ( isset( $data['profileHash'] ) ? $data['profileHash'] : '' ) );
			if ( ! hash_equals( trim( (string) MOBO_CORE_SHARED_MEDIA_PROFILE_HASH ), $profile_hash ) ) {
				return new WP_Error( 'mobo_shared_profile_mismatch', 'Shared media size profile does not match this WordPress installation.' );
			}
		}

		return $data;
	}

	private static function find_attachment( $image_guid ) {
		$query = new WP_Query(
			array(
				'post_type'              => 'attachment',
				'post_status'            => array( 'inherit', 'private' ),
				'fields'                 => 'ids',
				'posts_per_page'         => 1,
				'orderby'                => 'ID',
				'order'                  => 'DESC',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'meta_query'             => array(
					'relation' => 'AND',
					array( 'key' => '_mobo_shared_media', 'value' => '1' ),
					array(
						'relation' => 'OR',
						array( 'key' => 'image_guid', 'value' => $image_guid ),
						array( 'key' => 'img_guid', 'value' => $image_guid ),
					),
				),
			)
		);
		return ! empty( $query->posts[0] ) ? absint( $query->posts[0] ) : 0;
	}

	private static function normalize_image_id( $value ) {
		$value = strtolower( trim( sanitize_text_field( (string) $value ) ) );
		return preg_match( '/^[a-z0-9][a-z0-9_-]{2,190}$/', $value ) ? $value : '';
	}

	private static function shard( $image_guid ) {
		$hex = preg_replace( '/[^a-f0-9]/', '', strtolower( (string) $image_guid ) );
		$hex = str_pad( $hex, 4, '0' );
		return substr( $hex, 0, 2 ) . '/' . substr( $hex, 2, 2 );
	}

	private static function base_path() {
		if ( ! defined( 'MOBO_CORE_SHARED_MEDIA_PATH' ) ) {
			return '';
		}
		$path = wp_normalize_path( rtrim( (string) MOBO_CORE_SHARED_MEDIA_PATH, '/\\' ) );
		return '' !== $path && is_dir( $path ) && is_readable( $path ) ? $path : '';
	}

	private static function base_url() {
		if ( ! defined( 'MOBO_CORE_SHARED_MEDIA_URL' ) ) {
			return '';
		}
		return untrailingslashit( esc_url_raw( (string) MOBO_CORE_SHARED_MEDIA_URL ) );
	}

	private static function normalize_relative_path( $path ) {
		$path = str_replace( '\\', '/', trim( (string) $path ) );
		$path = ltrim( $path, '/' );
		if ( '' === $path || false !== strpos( $path, '../' ) || 0 === strpos( $path, '..' ) || false !== strpos( $path, "\0" ) ) {
			return '';
		}
		return preg_match( '#^[a-zA-Z0-9._/-]+$#', $path ) ? $path : '';
	}

	private static function resolve_existing_file( $relative ) {
		$relative = self::normalize_relative_path( $relative );
		if ( '' === $relative ) {
			return '';
		}
		$real = realpath( self::base_path() . '/' . $relative );
		return false !== $real && is_file( $real ) && is_readable( $real ) && self::is_path_inside_repository( $real )
			? wp_normalize_path( $real )
			: '';
	}

	private static function is_path_inside_repository( $file ) {
		$base = self::base_path();
		if ( '' === $base || ! is_string( $file ) || '' === trim( $file ) ) {
			return false;
		}
		$base_real = realpath( $base );
		$file_real = realpath( $file );
		if ( false === $base_real || false === $file_real ) {
			return false;
		}
		$base_real = trailingslashit( wp_normalize_path( $base_real ) );
		$file_real = wp_normalize_path( $file_real );
		return 0 === strpos( $file_real, $base_real );
	}

	private static function url_for_relative_file( $relative ) {
		$relative = self::normalize_relative_path( $relative );
		return '' !== $relative ? self::base_url() . '/' . str_replace( '%2F', '/', rawurlencode( $relative ) ) : '';
	}
}
